package server

import (
	"encoding/json"
	"fmt"
	"github.com/elysia-api/backend/protocol"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Real HTTP gateway, actual embedded definitions and full model bindings. The
// provider's response is fixed wire data, not generated by the target encoder.
func TestGatewayAuditTextMatrix(t *testing.T) {
	ids := []string{protocol.PresetChatCompletionsID, protocol.PresetResponsesID, protocol.PresetAnthropicID, protocol.PresetGeminiID}
	for _, upstreamID := range ids {
		t.Run(upstreamID, func(t *testing.T) {
			s, _ := newProtocolAdminTestServer(t)
			activateDiscoveryPresets(t, s)
			service, _ := s.protocolService()
			upstream, _ := service.Pin(upstreamID)
			var streaming bool
			calls := 0
			provider := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				calls++
				wanted := "text-decode-response"
				if streaming {
					wanted = "stream-text-decode"
				}
				for _, sample := range upstream.Definition().Samples {
					if sample.ID != wanted {
						continue
					}
					if !streaming {
						body, _ := sample.Input.ReadObject()
						switch upstreamID {
						case protocol.PresetChatCompletionsID:
							body["service_tier"] = protocol.StringValue("default")
							body["system_fingerprint"], _ = protocol.ParseValue([]byte("null"))
						case protocol.PresetResponsesID:
							body["store"], _ = protocol.ParseValue([]byte("false"))
						}
						value, _ := protocol.EncodeValue(body)
						w.Header().Set("Content-Type", "application/json")
						_, _ = w.Write(value.Bytes())
						return
					}
					w.Header().Set("Content-Type", "text/event-stream")
					var frames []protocol.Value
					_ = sample.Input.Decode(&frames)
					for _, frame := range frames {
						body, _ := frame.ReadObject()
						if upstreamID == protocol.PresetChatCompletionsID {
							body["service_tier"] = protocol.StringValue("default")
							body["system_fingerprint"], _ = protocol.ParseValue([]byte("null"))
						}
						value, _ := protocol.EncodeValue(body)
						if kind := body["type"]; !kind.IsZero() {
							var name string
							_ = kind.Decode(&name)
							fmt.Fprintf(w, "event: %s\n", name)
						}
						fmt.Fprintf(w, "data: %s\n\n", value.Bytes())
					}
					if upstreamID == protocol.PresetChatCompletionsID {
						_, _ = io.WriteString(w, "data: [DONE]\n\n")
					}
					return
				}
				t.Error("missing upstream fixture")
				w.WriteHeader(500)
			}))
			defer provider.Close()
			setupGatewayModel(t, s, upstream, provider.URL)
			for _, ingressID := range ids {
				for _, stream := range []bool{false, true} {
					t.Run(fmt.Sprintf("%s/stream=%v", ingressID, stream), func(t *testing.T) {
						streaming = stream
						before := calls
						path, body := "", ""
						switch ingressID {
						case protocol.PresetChatCompletionsID:
							path = "/chat/completions"
							body = fmt.Sprintf(`{"model":"group","max_tokens":32,"messages":[{"role":"user","content":"hi"}],"stream":%v,"stream_options":{"include_usage":true}}`, stream)
						case protocol.PresetResponsesID:
							path = "/responses"
							body = fmt.Sprintf(`{"model":"group","input":"hi","max_output_tokens":32,"store":false,"stream":%v}`, stream)
						case protocol.PresetAnthropicID:
							path = "/v1/messages"
							body = fmt.Sprintf(`{"model":"group","max_tokens":32,"messages":[{"role":"user","content":"hi"}],"max_tokens":32,"stream":%v}`, stream)
						case protocol.PresetGeminiID:
							path = "/v1beta/models/group:generateContent"
							if stream {
								path = "/v1beta/models/group:streamGenerateContent"
							}
							body = `{"generationConfig":{"maxOutputTokens":32},"contents":[{"role":"user","parts":[{"text":"hi"}]}]}`
						}
						r := httptest.NewRequest("POST", "/gateway/"+ingressID+path, strings.NewReader(body))
						r.Header.Set("Authorization", "Bearer gateway-test-token")
						rec := httptest.NewRecorder()
						s.engine.ServeHTTP(rec, r)
						if rec.Code != 200 || calls != before+1 || !strings.Contains(rec.Body.String(), "hi") || rec.Result().Trailer.Get("X-Elysia-Stream-Error") != "" {
							t.Fatalf("status=%d calls=%d trailer=%v body=%s", rec.Code, calls-before, rec.Result().Trailer, rec.Body)
						}
						ingress, _ := service.Pin(ingressID)
						if !stream {
							v, e := protocol.ParseValue(rec.Body.Bytes())
							if e != nil {
								t.Fatal(e)
							}
							if e = ingress.ValidateWireOutput(protocol.EncodeResponse, v); e != nil {
								t.Fatal(e)
							}
						} else {
							for _, line := range strings.Split(rec.Body.String(), "\n") {
								if !strings.HasPrefix(line, "data: {") {
									continue
								}
								v, e := protocol.ParseValue([]byte(strings.TrimPrefix(line, "data: ")))
								if e != nil {
									t.Fatal(e)
								}
								if e = ingress.ValidateWireOutput(protocol.EncodeEvent, v); e != nil {
									t.Fatal(e, line)
								}
							}
						}
						if dir := os.Getenv("ELYSIA_AUDIT_CAPTURE"); dir != "" {
							if e := os.MkdirAll(dir, 0700); e != nil {
								t.Fatal(e)
							}
							record := map[string]any{"upstream": upstreamID, "ingress": ingressID, "stream": stream, "body": rec.Body.String(), "headers": rec.Header()}
							raw, _ := json.Marshal(record)
							name := fmt.Sprintf("%s-%s-%v.json", upstreamID, ingressID, stream)
							if e := os.WriteFile(filepath.Join(dir, name), raw, 0600); e != nil {
								t.Fatal(e)
							}
						}
					})
				}
			}
		})
	}
}
